[package]
name = "common_graph"
version = "0.1.0"
edition = "2024"

description = "Common structural foundations for BezotCorp Rust graphs"
license = "Apache-2.0"
repository = "https://github.com/BezotCorp/common_graph"
readme = "README.md"
[dependencies]
chrono.workspace = true
serde.workspace = true
uuid.workspace = true
